# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='/media/default.png', upload_to=''),
        ),
    ]
